### ISSUE TITLE
Console Application doesn't work as .exe

### ISSUE THREAD

**Issue by ManderlaH** [MisterL-v/System-Identify#2]
It appears that the file was not converted to `.exe` correctly

**Comment by ManderlaH** [comment]
! Hinweis ! Meine Fehlermeldung wurde geänert! Ich bin nicht mehr verantwortlich für den jetzt aktuellen Inhalt 

- [ ]

**Comment by leonard-voss** [comment]
Done. You can find the fixed version under x64 / Versions in the Files.
